# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buoy.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbuoy.proto\x12\x0cregatta.msgs\"\xc0\x01\n\x0f\x42uoyObservation\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tbuoy_type\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\r\n\x05range\x18\x04 \x01(\x01\x12\x0f\n\x07\x62\x65\x61ring\x18\x05 \x01(\x01\x12\x13\n\x0b\x62\x65\x61ring_deg\x18\x06 \x01(\x01\x12\t\n\x01x\x18\x07 \x01(\x01\x12\t\n\x01y\x18\x08 \x01(\x01\x12\t\n\x01z\x18\t \x01(\x01\x12\x12\n\nrange_true\x18\n \x01(\x01\x12\x14\n\x0c\x62\x65\x61ring_true\x18\x0b \x01(\x01\"W\n\x14\x42uoyObservationArray\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12,\n\x05\x62uoys\x18\x02 \x03(\x0b\x32\x1d.regatta.msgs.BuoyObservationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'buoy_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BUOYOBSERVATION._serialized_start=29
  _BUOYOBSERVATION._serialized_end=221
  _BUOYOBSERVATIONARRAY._serialized_start=223
  _BUOYOBSERVATIONARRAY._serialized_end=310
# @@protoc_insertion_point(module_scope)
